name: Docker

on:
  release:
    types: [ released ]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $REGISTRY
      - id: get_version
        name: Get the release version
        uses: battila7/get-version-action@v2
        run: export TAG=${{ steps.get_version.outputs.version-without-v }}
      - name: Build image
        run: docker build . -t $IMAGE_NAME:$TAG
      - name: Push to DockerHub
        run: docker push $IMAGE_NAME:$TAG
