name: Docker

on:
  release:
    types: [ released ]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} $REGISTRY
      - name: Build image
        run: docker build . -t $IMAGE_NAME:$(cargo pkgid | cut -d "#" -f2)
      - name: Push to DockerHub
        run: docker push $IMAGE_NAME:$(cargo pkgid | cut -d "#" -f2)
